version: '3'

services:
  junior-day-site:
    container_name: juniorday_task
    build:
      context: .
      dockerfile: Dockerfile
    #expose:
    #  - 23007
    #ports:
    #  - "43003:43003"
    #environment:
      #- "VIRTUAL_HOST=jun.hitsecurity.ru"
      #- "VIRTUAL_PORT=8080"
    networks:
      - reverse_proxy
    restart: unless-stopped  
    command: php -S 0.0.0.0:43003

networks:
  reverse_proxy:
    external: true
